# Generated by Django 5.0 on 2023-12-28 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(choices=[('Mr.', 'Mr.'), ('Ms.', 'Ms.'), ('Mrs.', 'Mrs.'), ('Mx.', 'Mx.')], max_length=10)),
                ('firstName', models.CharField(blank=True, default='', max_length=60)),
                ('lastName', models.CharField(blank=True, default='', max_length=60)),
                ('email', models.CharField(blank=True, default='', max_length=60)),
                ('userName', models.CharField(blank=True, default='', max_length=60)),
            ],
        ),
    ]
